language: php

php:
    - 7.1

env:
  - TRAVIS_NODE_VERSION="4"

cache:
    yarn: true
    directories:
        - ~/.composer/cache/files

sudo: required

before_install:
    - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
    - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
    - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq yarn
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
    - composer update --prefer-dist
    - (cd tests/Application && yarn install)
    - npm install gulp gulp-concat gulp-chug gulp-debug gulp-if gulp-livereload gulp-order gulp-sass
    - npm install gulp-sourcemaps gulp-uglify gulp-uglifycss jquery lightbox2
    - npm install merge-stream semantic-ui-css yargs

before_script:
    - (cd tests/Application && bin/console doctrine:schema:create --env=test)
    - (mkdir tests/Application/web && cd tests/Application && bin/console assets:install web --env=test)
    - (cd tests/Application && yarn run gulp)

    - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1680x1050x16
    - export DISPLAY=:99

    - curl http://chromedriver.storage.googleapis.com/2.12/chromedriver_linux64.zip > chromedriver.zip && unzip chromedriver.zip

    - cp etc/travis/behat.yml ./behat.yml
    - vendor/bin/selenium-server-standalone -Dwebdriver.chrome.driver=chromedriver > /dev/null 2>&1 &
    - (cd tests/Application && bin/console server:run 127.0.0.1:8080 --env=test --quiet > /dev/null 2>&1 &)

script:
    - composer validate --strict --no-check-all
    - vendor/bin/phpspec run
    - vendor/bin/behat -vvv --no-interaction || vendor/bin/behat -vvv --no-interaction --rerun
    - vendor/bin/phpunit --coverage-clover coverage.clover --stderr --verbose

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
