services:
    sylius.google_tag_manager.block_event_listener.layout.javascripts:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@GtmPlugin/javascripts.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.javascripts, method: onBlockEvent }

    sylius.google_tag_manager.block_event_listener.layout.before_head:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@GtmPlugin/head.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.head, method: onBlockEvent }

    sylius.google_tag_manager.block_event_listener.layout.before_body:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@GtmPlugin/body.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.before_body, method: onBlockEvent }
